/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JBattlefield.Main;

import JBattlefield.ElementToPrint.PlayerString;
import JBattlefield.Model.Coordinate;
import JBattlefield.Model.Player;
import JBattlefield.Model.RGBColor;
import JBattlefield.Model.Ship;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        RGBColor color = new RGBColor(0, 0, 0);
        Ship s1 = new Ship(new Coordinate(2, 3), 2, 3);
        Ship s2 = new Ship(new Coordinate(9, 4), 2, 3);
        Ship s3 = new Ship(new Coordinate(13, 15), 4, 3);
        Ship s4 = new Ship(new Coordinate(4, 8), 1, 3);
        Ship s5 = new Ship(new Coordinate(13, 10), 3, 3);
        Ship s6 = new Ship(new Coordinate(4, 13), 2, 2);
        Set<Ship> play1 = new HashSet<>();
        Collections.addAll(play1, s1, s2, s3, s4, s5, s6);
        Player one = new Player("Alessio", play1, 25, color);
        PlayerString player = new PlayerString();
        System.out.printf(player.printOfElement(one));
    }
}
